from autogen_agentchat.agents import CodeExecutorAgent
from config.docker_executor import get_docker_executor

def get_code_executor_agent():
    """
    Returns an instance of the Code Executor Agent.
    This agent is designed to execute code in a Docker environment.
    It can be used to run code generated by other agents, such as the problem solver agent.
    """
    docker_executor = get_docker_executor()
    code_executor_agent = CodeExecutorAgent(
        name="CodeExecutorAgent",
        code_executor=docker_executor,
    )
    return code_executor_agent, docker_executor